version: "3.9"
    
services:
  db:
    build:
      context: ./database
    command: --ignore-db-dir=lost+found
    ports:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress3a
      MYSQL_DATABASE: wordpress3a
      MYSQL_USER: wordpress3a
      MYSQL_PASSWORD: wordpress3a
    
  myapp:
    depends_on:
      - db
    build:
      context: ./myapp
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data: {}
